# Netlify build configuration for PANN Frontend
[build]
  # Since your frontend is in a subfolder, set base directory
  base = "frontend/"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect rules for Vue.js SPA (handles client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache the main HTML file
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"